name: Update News Data and Qdrant Database

on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:     

jobs:
  update_data_and_database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  

      - name: Install dependencies
        run: pip install -r requirements.txt 

      - name: Create data directory 
        run: mkdir -p data/raw

      - name: Get articles from API
        env:
          NEWSAPI_TOKEN: ${{ secrets.NEWSAPI_TOKEN }}
        run: python scripts/get_articles_from_api.py

      - name: Commit and push updated data files
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add /home/runner/work/recommandation_articles_presse_LLM/recommandation_articles_presse_LLM/data/*
          
          # Vérifie s'il y a des fichiers à committer
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Updated data files"
            git push
          fi

      - name: Make Qdrant database
        env:
          GH_ACTIONS: ${{ secrets.GH_ACTIONS }}
          QDRANT_API_TOKEN: ${{ secrets.QDRANT_API_TOKEN }}
          QDRANT_HOST: ${{ secrets.QDRANT_HOST }}
          QDRANT_PORT: ${{ secrets.QDRANT_PORT }}
        run: python scripts/make_qdrant_database.py
