name: Update News Data and Qdrant Database

on:
  schedule:
    - cron: '0 0 * * *'  # Exécuter quotidiennement à minuit
  workflow_dispatch:     # Permettre le déclenchement manuel

jobs:
  update_data_and_database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Adaptez à votre version de Python

      - name: Install dependencies
        run: pip install -r requirements.txt 

      - name: Get articles from API
        env:
          NEWSAPI_TOKEN: ${{ secrets.NEWSAPI_TOKEN }}
        run: python scripts/get_articles_from_api.py

      - name: Commit and push updated data files
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add data/*
          git commit -m "Updated data files"
          git push

      - name: Make Qdrant database
        env:
          QDRANT_API_TOKEN: ${{ secrets.QDRANT_API_TOKEN }}
          QDRANT_HOST: ${{ secrets.QDRANT_HOST }}
          QDRANT_PORT: ${{ secrets.QDRANT_PORT }}
        run: python scripts/make_qdrant_database.py
