name: Daily Workflow

on:
  schedule:
    - cron: '0 22 * * *' # Runs at midnight UTC every day

jobs:
  run_scripts:
    name: Run Python Scripts
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Create data directory (if it doesn't exist)
        run: mkdir -p data/raw

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Execute get_articles_from_api.py
        env:
          NEWSAPI_TOKEN: ${{ secrets.NEWSAPI_TOKEN }}
        run: python scripts/get_articles_from_api.py
      
      - name: Execute make_qdrant_database.py
        env:
          QDRANT_API_TOKEN: ${{ secrets.QDRANT_API_TOKEN }}
        run: python scripts/make_qdrant_database.py

      - name: Push data to GitHub
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          git add ./data/*
          git commit -m "Update data"
          git push
